version: "3.8"
services:
  api:
    build: ./docker/api/
    tty: true
    volumes:
      - .:/go/src/github.com/rai-wtnb/accomplist-api
    ports:
      - '8080:8080'
    networks:
      - accomplist_link
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: accomplist
      POSTGRES_PASSWORD: accomplist-password
      POSTGRES_DB: accomplist
    ports:
      - 5432:5432
    networks:
      - accomplist_link

networks:
  accomplist_link:
    external: true
