version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15.2

    steps:
      - checkout

      - restore_cache:
          key: mod-{{ checksum "./api/go.sum" }}

      - run: cd ./api && go get
      - run: go test -v ./api/...
      - run: go build -o main ./api/main.go

      - store_artifacts:
          path: api
          destination: api

      - save_cache:
          key: mod-{{ checksum "./api/go.sum" }}
          paths:
            - $GOPATH/pkg/mod
