version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

executors:
  go-1-13-5:
    docker:
      - image: circleci/golang:1.13.5-node
        environment:
          GO111MODULE: "on"
          DB_HOST: "db"
          DB_PASS: "accomplist-password"
    working_directory: /go/src/github.com/rai-wtnb/accomplist-api/api

jobs:
  test:
    docker:
      - image: circleci/golang:1.13.5-node
        environment:
          DB_HOST: "localhost"
          DB_PASS: "accomplist-password"
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: accomplist
          POSTGRES_PASSWORD: accomplist-password
          POSTGRES_DB: accomplist
    steps:
      - checkout
      - run: go version
      - run: cd ./api && go test -v -cover -coverprofile=coverage.out ./...
      - codecov/upload:
          file: ./api/coverage.out
  build:
    executor: go-1-13-5
    steps:
      - checkout
      - run: cd ./api && go build
  build_image:
    docker:
      - image: docker:18.09.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install awscli
          command: |
            apk add --no-cache --update py-pip
            pip install awscli
      - run:
          name: login ecr
          command: |
            $(aws ecr get-login --no-include-email --region ap-northeast-1)
      - run:
          name: build image
          command: |
            docker build -f ./docker/prod/Dockerfile -t ${ECR_DOMAIN}:$CIRCLE_SHA1 -t ${ECR_DOMAIN}:latest .
      - run:
          name: push image
          command: |
            docker push ${ECR_DOMAIN}:$CIRCLE_SHA1
            docker push ${ECR_DOMAIN}:latest
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - run:
          name: install awscli
          command: |
            sudo pip install awscli
      - run:
          name: install jq
          command: |
            wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
            mv jq-linux64 jq
      - run:
          name: login
          command: |
            $(aws ecr get-login --no-include-email --region ap-northeast-1)
      - run:
          name: deploy
          command: |
            aws ecs describe-task-definition --task-definition accomplist-task | jq '.taskDefinition | { containerDefinitions: .containerDefinitions }' > definition.json
            aws ecs register-task-definition --execution-role-arn arn:aws:iam::327222865572:role/ecs-task-role --family accomplist-task --cli-input-json file://definition.json
            aws ecs update-service --cluster accomplist-ecs-cluster --service accomplist-api --task-definition accomplist-task


workflows:
  version: 2
  test and build:
    jobs:
      - test
      - build
      - build_image:
          requires:
            - build
          filters:
              branches:
                only:
                  - main
      - deploy:
          requires:
            - build_image
          filters:
            branches:
                only:
                  - main
