version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

executors:
  go-1-13-5:
    docker:
      - image: circleci/golang:1.13.5-node
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/rai-wtnb/accomplist-api/api

jobs:
  test:
    executor: go-1-13-5
    steps:
      - checkout
      - run: go version
      - run: go test -v -cover -coverprofile=coverage.out ./...
      - codecov/upload:
          file: ./coverage.out
  build:
    executor: go-1-13-5
    steps:
      - checkout
      - run: cd ./api && go build

workflows:
  version: 2
  test and build:
    jobs:
      - test:
          filters:
              branches:
                only:
                  - main
      - build:
          filters:
              branches:
                only:
                  - main
